data:
  image: "busybox"
  volumes:
    - /var/lib/mysql

db:
  image: 'mysql:latest'
  environment:
    MYSQL_ROOT_PASSWORD: %%FILL_IN_THIS%%
  volumes_from:
    - data

web:
  build: ./
  command: 'bundle exec puma -p 3000'
  environment:
    RAILS_ENV: development
  volumes:
    - .:/usr/src/app
  ports:
    - '3000:3000'
  links:
    - db
