development:
    email:
        server: mail.conradchu.com
        port: 2525
        domain:
        authentication: login
        username: smtp+conradchu.com
        password: smtprules
        delivery_method: :smtp
        recipient_alias_email: alias@domain.com
        from_email: youremail@domain.com        

production:
    email:
        server: localhost
        port:
        domain:
        authentication: 
        username: 
        password: 
        delivery_method: :sendmail
        recipient_alias_email: alias@domain.com
        from_email: youremail@domain.com
