development:
    email:
        server: mail.conradchu.com
        port: 2525
        domain:
        authentication: login
        username: smtp+conradchu.com
        password: smtprules
        delivery_method: :smtp           

production:
    email:
        server: localhost
        port:
        domain:
        authentication: 
        username: 
        password: 
        delivery_method: :sendmail
