development:
        email:
                server: localhost
                port: 25
                domain: www.gracepointonline.org
                authentication: login
                username:
                password: 
                delivery_method: :sendmail                
production:
        email:
                server: localhost
                port: 25
                domain: www.gracepointonline.org
                authentication: login
                username:
                password: 
                delivery_method: :sendmail