development:
    email:
        server: 
        port: 25
        domain:
        authentication: login
        username: 
        password: 
        delivery_method: :smtp
        recipient_alias_email: alias@domain.com
        from_email: youremail@domain.com        
    links:
        rss: http://www.yoursite.com/posts/rss    
        support: http://www.yoursupportsite.com

production:
    email:
        server: 
        port: 25
        domain:
        authentication: login
        username: 
        password: 
        delivery_method: :smtp
        recipient_alias_email: alias@domain.com
        from_email: youremail@domain.com        
    links:
        rss: http://www.yoursite.com/posts/rss    
        support: http://www.yoursupportsite.com