---

development: &default
  secret_key_base: <%= ENV['SECRET_TOKEN'] %>
  google_oauth_client_id: <%= ENV['GOOGLE_OAUTH_CLIENT_ID'] %>
  google_oauth_client_secret: <%= ENV['GOOGLE_OAUTH_CLIENT_SECRET'] %>

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
