# Emails
dev_email: conrad.chu@gpmail.org

# Number of times to notify users a week
notify_frequency: 2

# Notification Digest Email
digest_from_email:            gracelist@gpmail.org
digest_recipient_alias_email: conrad.chu@gpmail.org